spring.application.name=demo

# MySQL Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret = 7e98c00f6c259af441bd82143bf0dea5f8d8d467718318e4fc6635660ea0de48
jwt.expiration = 36000000000


sms.api.key = 1sk_DeEsV9HMppk9RSH7DMDS21RlvLNUhDN5VMwIXqCxgeTRxpZpByqD1HOOxqzH7HDAmxJ4lgjCoMwOaFS93mHaCF
sms.base-url = https://1sms.az/api/v1/sms/otp